### ISSUE TITLE
how to use confusion matrix and f1 score functions?

### ISSUE THREAD

**Issue by jaraheel** [AdarshKumar712/Metrics.jl#4]
Hi,
I have the following code:

y_pred = ones(k)
y_true = ones(k)

Metrics.f_beta_score(y_pred, y_true) gives the following error:
ERROR: type Int64 has no field I
Stacktrace:
 [1] getproperty
   @ ./Base.jl:42 [inlined]
 [2] onecold(y::Vector{Float64})
   @ Metrics ~/.julia/packages/Metrics/QuZ3b/src/Classification.jl:31
 [3] confusion_matrix(y_pred::Vector{Float64}, y_true::Vector{Float64})
   @ Metrics ~/.julia/packages/Metrics/QuZ3b/src/Classification.jl:44
 [4] TFPN(y_pred::Vector{Float64}, y_true::Vector{Float64})
   @ Metrics ~/.julia/packages/Metrics/QuZ3b/src/Classification.jl:58
 [5] recall(y_pred::Vector{Float64}, y_true::Vector{Float64}; avg_type::String, sample_weights::Nothing)
   @ Metrics ~/.julia/packages/Metrics/QuZ3b/src/Classification.jl:195
 [6] f_beta_score(y_pred::Vector{Float64}, y_true::Vector{Float64}; β::Int64, avg_type::String, sample_weights::Nothing)
   @ Metrics ~/.julia/packages/Metrics/QuZ3b/src/Classification.jl:230
 [7] f_beta_score(y_pred::Vector{Float64}, y_true::Vector{Float64})
   @ Metrics ~/.julia/packages/Metrics/QuZ3b/src/Classification.jl:230
 [8] top-level scope
   @ REPL[12]:1

Same error occurs when I try functions like cohen_kappa, f_beta_score etc. Can you please show me how to use f_beta_score and report_stats functions?

Furthermore, do these work with multi class classification? In the documentation it is mentioned one-hot encoded vectors for predictions and truths.

**Comment by AdarshKumar712** [comment]
I sincerely apologise for such a late reply. I believe by now, you might have figured it out yourself. Still others who might possibly face this issue, I am writing here.

Actually the function expects MultiClass Classification problem i.e.  It expects `y_true` and `y_pred` as Matrix of shape [num_classes, num_samples]. That's why it was giving that error.

For similar example, you can check out: https://github.com/AdarshKumar712/Metrics.jl/issues/5

**Comment by jaraheel** [comment]
thank you very much :)
